version: "3.4"

services:
  home-peaceful:
    image: itzg/minecraft-bedrock-server
    environment:
      # https://minecraft.fandom.com/wiki/Server.properties#Bedrock_Edition_3
      EULA: "TRUE"      
      GAMEMODE: survival # survival, creative, adventure
      DIFFICULTY: peaceful # peaceful, easy, normal hard
      ALLOW_CHEATS: "true" # true, false
      SERVER_NAME: "Peaceful Server"
    ports:
      - 19132:19132/udp
    volumes:
      - ./data/peaceful1:/data
    tty: true
    stdin_open: true
    restart: unless-stopped


# volumes:
#   mc: {}
